name: Docker Image CI

on:
 push:
    tags:
      - '*'

env:
  version-tag: "${{ github.ref_name }}"

jobs:

  plx-to-kilosort:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: ninjaben/plx-to-kilosort:${{ env.version-tag }}
